app:
  datasource:
    db:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/honeybee?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 10
        maximum-pool-size: 200
        auto-commit: true
        idle-timeout: 30000
        pool-name: DataPoolHikari
        max-lifetime: 180000
        connection-timeout: 30000
        connection-test-query: SELECT 1
  config:
    upload: /Users/william/development/test-spaces/
    api: http://127.0.0.1:18083/api
  cors:
    urls:
      - http://localhost:9527
      - http://127.0.0.1:9527
      - http://127.0.0.1:18082
  security:
    token:
      issuer: honeybee
      secret: honeybee
      expires: 180
spring:
  redis:
    host: 192.168.188.129
    port: 6379
    database: 0
    password:
    timeout: 10000
    pool:
      maxIdle: 5
      minIdle: 5
      maxActive: 100
      maxWait: 10
