type: postgresql
version: 10
connector: com.stackstech.honeybee.connector.postgresql.PostgreSQLConnector
config:
  driver-class-name: org.postgresql.Driver
  jdbcUrl: "jdbc:postgresql://localhost:5432/DatabaseName"
  username: root
  password: root