type: mysql
version: 5.7
connector: com.stackstech.honeybee.connector.mysql.MsSQLConnector
config:
  driver-class-name: com.mysql.jdbc.Driver
  jdbcUrl: "jdbc:mysql://127.0.0.1:3306/DatabaseName?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull"
  username: root
  password: root