type: mysql
version: 5.7
connector: com.stackstech.honeybee.connector.mysql.MsSQLConnector
config:
  driver-class-name: com.mysql.jdbc.Driver
  jdbcUrl: "jdbc:mysql://127.0.0.1:3306/honeybee?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull"
  username: root
  password: 123456
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    minimum-idle: 10
    maximum-pool-size: 200
    auto-commit: true
    idle-timeout: 30000
    pool-name: DataPoolHikari
    max-lifetime: 180000
    connection-timeout: 30000
    connection-test-query: SELECT 1