spring:
  redis:
    host: 192.168.188.129
    port: 6379
    password:
    database: 0
    timeout: 1000
    pool:
      max-active: 20
      max-wait: 10
      max-idle: 8
      min-idle: 0
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/honeybee?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    filters: stat
    max-active: 100
    initial-size: 10
    max-wait: 60000
    min-idle: 1
    validation-query: SELECT 'x'

server:
  path:
    upload: /Users/william/development/test-spaces/
    conf: /Users/william/development/workspace/projects/honeybee/honeybee-cloud-server/conf
  api: http://127.0.0.1:18083/api
  datacache:
    expires: 300

cors:
  urls:
    - http://localhost:9527
    - http://127.0.0.1:9527
    - http://localhost:8080
    - http://127.0.0.1:8080

security:
  token:
    issuer: honeybee
    secret: honeybee
    expires: 180
debug: true